#!/bin/sh

case "$1" in
n) firefox-esr --new-window --private-window & ;;
a) firefox-esr --new-window --private-window "https://www.duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1" & ;;
d) firefox-esr --new-window --private-window "https://www.duckduckgo.com" & ;;
g) firefox-esr --new-window --private-window "https://www.google.com" & ;;
G) firefox-esr --new-window --private-window "https://www.github.com/login" & ;;
m) firefox-esr --new-window --private-window "https://www.gmail.com" & ;;
d) firefox-esr --new-window --private-window "https://www.drive.google.com" & ;;
w) firefox-esr --new-window --private-window "https://web.whatsapp.com" & ;;
s) firefox-esr --new-window --private-window "https://open.spotify.com" & ;;
y) firefox-esr --new-window --private-window "https://youtube.com" & ;;
e) firefox-esr --new-window --private-window "https://translate.google.co.uk/?sl=en&tl=es&op=translate" & ;;
E) firefox-esr --new-window --private-window "https://translate.google.co.uk/?sl=es&tl=en&op=translate" & ;;
esac
