#!/bin/sh

case "$@" in
"t") fish -c "fsignal 0" ;;
"m") fish -c "fsignal 1" ;;
"s") fish -c "fsignal 2" ;;
"w") fish -c "fsignal 3" ;;
"d") fish -c "fsignal 4" ;;
"b") fish -c "fsignal 5" ;;
"B") fish -c "fsignal 6" ;;
"g") fish -c "fsignal 7" ;;
"r") fish -c "fsignal 8" ;;
"h") fish -c "fsignal 9" ;;
"l") fish -c "fsignal 10" ;;
"M") fish -c "fsignal 12" ;;
"F") fish -c "fsignal 13" ;;
"f") fish -c "fsignal 14" ;;

esac
